ITEM.name = "Moonshine"
ITEM.desc = "Moonshine"
ITEM.model = "models/props_junk/garbage_glassbottle003a.mdl"
ITEM.uniqueID = "Moonshine"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 20
ITEM.desc = "Has a 20 Percent ABV."
ITEM.sound = "eating_and_drinking/drinking.wav"