net.Receive("sergeant_dornan", function()
    local player_name = net.ReadString()

    talkablenpcs.dialog("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave", function(ply)
        talkablenpcs.dialogframe("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave")
        talkablenpcs.playsound("vo/k_lab/ba_headhumper01.wav")
        talkablenpcs.dialogtext("Welcome to Camp Navarro. So, your're the new replacement. What's your name, private?")

        talkablenpcs.dialogbutton("Private " .. player_name, 40, function()
            self:Remove()
            talkablenpcs.dialogframe("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave")
            talkablenpcs.dialogtext("What was that? Did you forget something, maggot?")
            talkablenpcs.playsound("vo/k_lab/ba_headhumper02.wav")

            talkablenpcs.dialogbutton("My name is " .. player_name .. ", Sir!", 40, function()
                self:Remove()
                talkablenpcs.dialogframe("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave")
                talkablenpcs.dialogtext("I am not a Sir. I work for a living, you mo-ron. You will call me Sergeant, or Sergeant Dornan. Do you understand me!")
                talkablenpcs.playsound("vo/k_lab/ba_headhumper01.wav")

                talkablenpcs.dialogbutton("Yes, Sergeant!", 40, function()
                    self:Remove()
                    talkablenpcs.dialogframe("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave")
                    talkablenpcs.dialogtext("Outstanding. Proceed on the double to the hangar where you will stand guard duty. You will do a fine job. Do you understand?")
                    talkablenpcs.playsound("vo/k_lab/ba_headhumper02.wav")

                    talkablenpcs.dialogbutton("What am I guarding there, Sergeant?", 40, function()
                        self:Remove()
                        talkablenpcs.dialogframe("Sergeant Dornan", "models/yates/apa_f.mdl", "Sergeant", "Enclave")
                        talkablenpcs.dialogtext("You mo-ron, you are not to question my orders! When I say jump, you jump! When I say fight, you fight! I tell you to die for your country, then you will certainly die! Have I made myself clear?")
                        talkablenpcs.playsound("vo/k_lab/ba_headhumper01.wav")

                        talkablenpcs.dialogbutton("Yes, Sergeant! (Close)", 40, function()
                            self:Remove()
                        end)
                    end)
                end)
            end)
        end)
    end)
end)