--Plank
list.Add("OverrideMaterials", "plank1")
list.Add("OverrideMaterials", "plank2")
list.Add("OverrideMaterials", "plank3")
--Wall
list.Add("OverrideMaterials", "wall1")
list.Add("OverrideMaterials", "wall2")
list.Add("OverrideMaterials", "wall3")
list.Add("OverrideMaterials", "wall4")
list.Add("OverrideMaterials", "wall5")
list.Add("OverrideMaterials", "wall6")
list.Add("OverrideMaterials", "wall7")
--Metal
list.Add("OverrideMaterials", "metal")
list.Add("OverrideMaterials", "metal1")
list.Add("OverrideMaterials", "metal2")
--Dirt
list.Add("OverrideMaterials", "dirt")
list.Add("OverrideMaterials", "dirt1")
--Grass
list.Add("OverrideMaterials", "grass")
--Ice
list.Add("OverrideMaterials", "ice")
--Water
list.Add("OverrideMaterials", "water")
--Tiles
list.Add("OverrideMaterials", "tiles")
--Snow
list.Add("OverrideMaterials", "snow")
--Rock
list.Add("OverrideMaterials", "rock")
list.Add("OverrideMaterials", "rock1")
list.Add("OverrideMaterials", "rock2")
list.Add("OverrideMaterials", "rock3")
--Plaster
list.Add("OverrideMaterials", "plaster")
list.Add("OverrideMaterials", "plaster1")
list.Add("OverrideMaterials", "plaster2")
list.Add("OverrideMaterials", "plaster3")
--Roofing
list.Add("OverrideMaterials", "roofing")
list.Add("OverrideMaterials", "roofing1")
list.Add("OverrideMaterials", "roofing2")
--Walpaper
list.Add("OverrideMaterials", "wallpaper")
list.Add("OverrideMaterials", "wallpaper1")
list.Add("OverrideMaterials", "wallpaper2")
list.Add("OverrideMaterials", "wallpaper3")
list.Add("OverrideMaterials", "wallpaper4")
list.Add("OverrideMaterials", "wallpaper5")
list.Add("OverrideMaterials", "wallpaper6")
list.Add("OverrideMaterials", "wallpaper7")
-- Woodplace/stone
list.Add("OverrideMaterials", "wood")
list.Add("OverrideMaterials", "wood2")
list.Add("OverrideMaterials", "wood3")
list.Add("OverrideMaterials", "woodstone")
list.Add("OverrideMaterials", "woodstone1")
list.Add("OverrideMaterials", "woodplace")
list.Add("OverrideMaterials", "woodplace1")
list.Add("OverrideMaterials", "woodplace2")
list.Add("OverrideMaterials", "woodplace3")
list.Add("OverrideMaterials", "woodplace4")
list.Add("OverrideMaterials", "woodplace5")
list.Add("OverrideMaterials", "woodplace6")
list.Add("OverrideMaterials", "woodplace7")
list.Add("OverrideMaterials", "woodplace8")
list.Add("OverrideMaterials", "woodplace9")
list.Add("OverrideMaterials", "woodplace10")
list.Add("OverrideMaterials", "woodplace11")
list.Add("OverrideMaterials", "woodplace12")
list.Add("OverrideMaterials", "woodplace13")
list.Add("OverrideMaterials", "woodplace14")
list.Add("OverrideMaterials", "woodplace15")
list.Add("OverrideMaterials", "woodplace16")
list.Add("OverrideMaterials", "woodplace17")
list.Add("OverrideMaterials", "woodplace18")
list.Add("OverrideMaterials", "woodplace19")
--Stone
list.Add("OverrideMaterials", "stone")
list.Add("OverrideMaterials", "stoneplace1")
list.Add("OverrideMaterials", "stoneplace2")
list.Add("OverrideMaterials", "stoneplace3")
list.Add("OverrideMaterials", "stoneplace4")
list.Add("OverrideMaterials", "stoneplace5")
list.Add("OverrideMaterials", "stoneplace6")
list.Add("OverrideMaterials", "stoneplace7")
list.Add("OverrideMaterials", "stoneplace8")
list.Add("OverrideMaterials", "stoneplace9")
--Concreteplace
list.Add("OverrideMaterials", "concreteplace")
list.Add("OverrideMaterials", "concreteplace1")
list.Add("OverrideMaterials", "concreteplace2")
list.Add("OverrideMaterials", "concreteplace3")
list.Add("OverrideMaterials", "concreteplace4")
list.Add("OverrideMaterials", "concreteplace5")
list.Add("OverrideMaterials", "concreteplace6")

-- BIGMATERIALS UPDATE - GAME

-- 1. Mafia II
list.Add("OverrideMaterials", "asfaltm")
list.Add("OverrideMaterials", "boards1m")
list.Add("OverrideMaterials", "boards2m")
list.Add("OverrideMaterials", "boardsm")
list.Add("OverrideMaterials", "bricktilesm")
list.Add("OverrideMaterials", "brickwall1m")
list.Add("OverrideMaterials", "concretetiles1m")
list.Add("OverrideMaterials", "concretetilesm")
list.Add("OverrideMaterials", "concretewallm")
list.Add("OverrideMaterials", "dirtm")
list.Add("OverrideMaterials", "stonetiles1m")
list.Add("OverrideMaterials", "stonetiles2m")
list.Add("OverrideMaterials", "stonetilesm")
list.Add("OverrideMaterials", "woodenfloorm")
-------------------------------------------------
-- 2. The Elder Scrolls III: Morrowind
list.Add("OverrideMaterials", "boards1w")
list.Add("OverrideMaterials", "boards2w")
list.Add("OverrideMaterials", "boards3w")
list.Add("OverrideMaterials", "boards4w")
list.Add("OverrideMaterials", "boards5w")
list.Add("OverrideMaterials", "boardsw")
list.Add("OverrideMaterials", "brickwall1w")
list.Add("OverrideMaterials", "brickwall2w")
list.Add("OverrideMaterials", "brickwall3w")
list.Add("OverrideMaterials", "brickwallw")
list.Add("OverrideMaterials", "concretewallw")
list.Add("OverrideMaterials", "metalplate1w")
list.Add("OverrideMaterials", "metalplatew")
list.Add("OverrideMaterials", "stonetilesw")
list.Add("OverrideMaterials", "stonewall1w")
list.Add("OverrideMaterials", "stonewall2w")
list.Add("OverrideMaterials", "stonewall3w")
list.Add("OverrideMaterials", "stonewall4w")
list.Add("OverrideMaterials", "stonewallw")
list.Add("OverrideMaterials", "woodenfloorw")
list.Add("OverrideMaterials", "woodenwallw")
-------------------------------------------------
-- 3. Grand Theft Auto V
list.Add("OverrideMaterials", "concreteg")
list.Add("OverrideMaterials", "grassg")
list.Add("OverrideMaterials", "gravelg")
list.Add("OverrideMaterials", "metall1g")
list.Add("OverrideMaterials", "metall2g")
list.Add("OverrideMaterials", "metallg")
list.Add("OverrideMaterials", "parkingg")
list.Add("OverrideMaterials", "roadg")
list.Add("OverrideMaterials", "roofg")
list.Add("OverrideMaterials", "wall1g")
list.Add("OverrideMaterials", "wall2g")
list.Add("OverrideMaterials", "wallg")
list.Add("OverrideMaterials", "wood1g")
list.Add("OverrideMaterials", "wood2g")
list.Add("OverrideMaterials", "woodg")
-- 15 materials
-------------------------------------------------
-- 4. Call of Duty 4: Modern Warfare
list.Add("OverrideMaterials", "barrierc")
list.Add("OverrideMaterials", "clinderblockc")
list.Add("OverrideMaterials", "floor1c")
list.Add("OverrideMaterials", "floor2c")
list.Add("OverrideMaterials", "floor3c")
list.Add("OverrideMaterials", "floor4c")
list.Add("OverrideMaterials", "floorc")
list.Add("OverrideMaterials", "plaster1c")
list.Add("OverrideMaterials", "plasterc")
list.Add("OverrideMaterials", "stonec")
list.Add("OverrideMaterials", "walkc")
list.Add("OverrideMaterials", "wall1c")
list.Add("OverrideMaterials", "wall2c")
list.Add("OverrideMaterials", "wallc")
-- 14 materials