ITEM.name = "Drying Rack"
ITEM.model = "models/props_wasteland/kitchen_shelf001a.mdl"
ITEM.desc = "Use this Rack to Dry Legal Stuff."
ITEM.price = 0.41
ITEM.width = 1
ITEM.height = 1
ITEM.uniqueID = "dryingrack"
ITEM.entdrop = "drying_rack"
ITEM.noBusiness = true